### ISSUE TITLE
Does the batch_size have to be at least as large as the sequence length ?

### ISSUE THREAD

**Issue by ParitoshParmar** [junhyukoh/caffe-lstm#19]
I am trying to use video frames as input to the network.
For example, if, on average, the video length is 160 frames, then, does this mean that batch_size should be at least 160, so that the LSTM layer has information of all the frames in the video sequence ?
I am guessing that if the batch_size is less than average video length, then the sequence would be broken and the LSTM layer would be learning from incomplete sequences. Am I correct ?

**Comment by junhyukoh** [comment]
Yes.

**Comment by ParitoshParmar** [comment]
Thank you @junhyukoh
