### ISSUE TITLE
How to do Many-to-One LSTM learning?

### ISSUE THREAD

**Issue by ParitoshParmar** [junhyukoh/caffe-lstm#21]
I want to feed a sequence of 10 vectors into the LSTM and for those 10 inputs I have 1 output label. I don't have (and don't want to have) labels for intermediate results from LSTM (as such, I just want 1 final output from LSTM for 10 input vectors). Illustrated below:

**Input vector   -->     Label**
vector_1    -->           n/a
vector_2    -->           n/a
vector_3    -->           n/a
    .
    .
    .
vector_10   -->           final_label

Is it possible to do something like this using this implementation of LSTM's ? If so, can you please just give a starting point ?

**Comment by junhyukoh** [comment]
The output of LSTM layer is concatenation of the whole hidden units (h_1, ... , h_T).
You can add more layers on top of that to select h_T out of h_1, ..., h_T.
I think either one of these should work:
1) Filter layer (select T-th blob)
2) Slice layer (divide into 1-(T-1) steps and T-th step) + Silence layer applied to 1-(T-1) steps.

**Comment by ParitoshParmar** [comment]
@junhyukoh Filter layer seems to be doing the job. Thanks a lot!

**Comment by ra1995** [comment]
@ParitoshParmar @junhyukoh  can you please share the prototxt or a snippet of it. It would help me a lot. Thanks
I cant seem to find any example on how to use a filter layer in a prototxt file

**Comment by paritosh1** [comment]
@ra1995 To use filter layer, you need to have a filter mask like this:
#---------------------filter mask----------------------
layer {
  name: "clip_data"
  type: "ImageData"
  top: "dummy"
  top: "filter_mask"

  image_data_param {
    source: "filter_mask.txt"
    batch_size: 45
    shuffle: false
  }
}

layer {
  name: "Silence"
  type: "Silence"
  bottom: "dummy"
}

and then:

#-------------main filter layer-----------------
layer {
  name: "filter"
  type: "Filter"
  bottom: "fc"
  bottom: "filter_mask"
  top: "filtered_fc"
}

**Comment by ParitoshParmar** [comment]
@ra1995 To use filter layer, you need to have a filter mask like this:
#---------------------filter mask----------------------
layer {
name: "clip_data"
type: "ImageData"
top: "dummy"
top: "filter_mask"

image_data_param {
source: "filter_mask.txt"
batch_size: 45
shuffle: false
}
}

layer {
name: "Silence"
type: "Silence"
bottom: "dummy"
}

and then:

#-------------main filter layer-----------------
layer {
name: "filter"
type: "Filter"
bottom: "fc"
bottom: "filter_mask"
top: "filtered_fc"
}

filter_mask.txt would be something like this:
0
0
0
0
1
where, 0 means you would be filtering OUT (throwing away), 1 means you would consider it.

**Comment by ra1995** [comment]
@ParitoshParmar thanks, just one more thing, will the top 'filtered_fc' have the same dimensions as 'fc' or will it be just what we are keeping in the mask?

**Comment by ParitoshParmar** [comment]
Let's suppose you are filtering out `m`th element (each of which is `p`-dimensional), then what you'd passing through the filter can be thought of as an `m` * `p` matrix. The output would be just one `p`-dimensional vector (`m`the element). Eg. below:

```
weqwerqwrqwr
asdasdasdasda
zxczxvzxvzvzvz
121313213211
```
---------------
filter layer - filter mask: `0 0 0 1`
---------------
`121313213211` <- output

**Comment by ra1995** [comment]
@ParitoshParmar thanks for all the help :)
